### ISSUE TITLE
Разработка взаимодействия с проверяющей средой

### ISSUE THREAD

**Issue by romanphilipskikh** [hhru-school/checkup-extension#30]
Передача решения на проверку в утилиту (js-среду) и получение от неё результата.

**Comment by romanphilipskikh** [comment]
Надо подумать над структурой хранения результатов в БД, чтобы проводить какой то минимальный анализ (тесты прошли или нет) и вывод результата пользователю (например, какой тест упал, или почему его решение не принято, что ему надо исправить).

Утилита выдает решения в таком виде:

Для задач на верстку:
{
    "numFailedTestSuites": 1,
    "numFailedTests": 1,
    "numPassedTestSuites": 0,
    "numPassedTests": 0,
    "numPendingTestSuites": 0,
    "numPendingTests": 0,
    "numRuntimeErrorTestSuites": 0,
    "numTodoTests": 0,
    "numTotalTestSuites": 1,
    "numTotalTests": 1,
    "openHandles": [],
    "snapshot": {
        "added": 0,
        "didUpdate": false,
        "failure": true,
        "filesAdded": 0,
        "filesRemoved": 0,
        "filesRemovedList": [],
        "filesUnmatched": 1,
        "filesUpdated": 0,
        "matched": 0,
        "total": 1,
        "unchecked": 0,
        "uncheckedKeysByFile": [],
        "unmatched": 1,
        "updated": 0
    },
    "startTime": 1682837648097,
    "success": false,
    "testResults": [{
            "assertionResults": [{
                    "ancestorTitles": ["Решение"],
                    "duration": 163,
                    "failureDetails": [{
                            "matcherResult": {
                                "message": "Expected image to match or be a close match to snapshot but was 0.5291666666666667% different from snapshot (127 differing pixels).\n\u001b[1m\u001b[31mSee diff for details:\u001b[39m\u001b[22m \u001b[31mE:\\projects\\HH\\checkup-extension\\checker-js\\submission\\__diff__\\test-js-решение-совпадает-с-примером-1-snap-diff.png\u001b[39m",
                                "pass": false
                            }
                        }
                    ],
                    "failureMessages": ["Error: Expected image to match or be a close match to snapshot but was 0.5291666666666667% different from snapshot (127 differing pixels).\n\u001b[1m\u001b[31mSee diff for details:\u001b[39m\u001b[22m \u001b[31mE:\\projects\\HH\\checkup-extension\\checker-js\\submission\\__diff__\\test-js-решение-совпадает-с-примером-1-snap-diff.png\u001b[39m\n    at Object.toMatchImageSnapshot (E:\\projects\\HH\\checkup-extension\\checker-js\\submission\\test.js:29:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],
                    "fullName": "Решение совпадает с примером",
                    "invocations": 1,
                    "location": null,
                    "numPassingAsserts": 0,
                    "retryReasons": [],
                    "status": "failed",
                    "title": "совпадает с примером"
                }
            ],
            "endTime": 1682837649612,
            "message": "\u001b[1m\u001b[31m  \u001b[1m● \u001b[22m\u001b[1mРешение › совпадает с примером\u001b[39m\u001b[22m\n\n    Expected image to match or be a close match to snapshot but was 0.5291666666666667% different from snapshot (127 differing pixels).\n    \u001b[1m\u001b[31mSee diff for details:\u001b[39m\u001b[22m \u001b[31mE:\\projects\\HH\\checkup-extension\\checker-js\\submission\\__diff__\\test-js-решение-совпадает-с-примером-1-snap-diff.png\u001b[39m\n\u001b[2m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 27 |\u001b[39m     \u001b[36mconst\u001b[39m image \u001b[33m=\u001b[39m \u001b[36mawait\u001b[39m page\u001b[33m.\u001b[39mscreenshot()\u001b[33m;\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 28 |\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[2m\u001b[39m\u001b[90m 29 |\u001b[39m     expect(image)\u001b[33m.\u001b[39mtoMatchImageSnapshot({\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m    |\u001b[39m                   \u001b[31m\u001b[1m^\u001b[22m\u001b[2m\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 30 |\u001b[39m       failureThreshold\u001b[33m:\u001b[39m \u001b[35m0.0\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 31 |\u001b[39m       failureThresholdType\u001b[33m:\u001b[39m \u001b[32m\"percent\"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 32 |\u001b[39m     })\u001b[33m;\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.toMatchImageSnapshot (\u001b[22m\u001b[2m\u001b[0m\u001b[36msubmission/test.js\u001b[39m\u001b[0m\u001b[2m:29:19)\u001b[22m\u001b[2m\u001b[22m\n",
            "name": "E:\\projects\\HH\\checkup-extension\\checker-js\\submission\\test.js",
            "startTime": 1682837648152,
            "status": "failed",
            "summary": ""
        }
    ],
    "wasInterrupted": false
}
Для задач на знание DOM API:
{
    "numFailedTestSuites": 0,
    "numFailedTests": 0,
    "numPassedTestSuites": 1,
    "numPassedTests": 3,
    "numPendingTestSuites": 0,
    "numPendingTests": 0,
    "numRuntimeErrorTestSuites": 0,
    "numTodoTests": 0,
    "numTotalTestSuites": 1,
    "numTotalTests": 3,
    "openHandles": [],
    "snapshot": {
        "added": 0,
        "didUpdate": false,
        "failure": false,
        "filesAdded": 0,
        "filesRemoved": 0,
        "filesRemovedList": [],
        "filesUnmatched": 0,
        "filesUpdated": 0,
        "matched": 2,
        "total": 2,
        "unchecked": 0,
        "uncheckedKeysByFile": [],
        "unmatched": 0,
        "updated": 0
    },
    "startTime": 1682837994403,
    "success": true,
    "testResults": [{
            "assertionResults": [{
                    "ancestorTitles": ["Решение"],
                    "duration": 4,
                    "failureDetails": [],
                    "failureMessages": [],
                    "fullName": "Решение должно существовать и быть функцией",
                    "invocations": 1,
                    "location": null,
                    "numPassingAsserts": 2,
                    "retryReasons": [],
                    "status": "passed",
                    "title": "должно существовать и быть функцией"
                }, {
                    "ancestorTitles": ["Решение"],
                    "duration": 11,
                    "failureDetails": [],
                    "failureMessages": [],
                    "fullName": "Решение должно отрабатывать, когда работа отсутствует",
                    "invocations": 1,
                    "location": null,
                    "numPassingAsserts": 2,
                    "retryReasons": [],
                    "status": "passed",
                    "title": "должно отрабатывать, когда работа отсутствует"
                }, {
                    "ancestorTitles": ["Решение"],
                    "duration": 10,
                    "failureDetails": [],
                    "failureMessages": [],
                    "fullName": "Решение должно отрабатывать - 1",
                    "invocations": 1,
                    "location": null,
                    "numPassingAsserts": 2,
                    "retryReasons": [],
                    "status": "passed",
                    "title": "должно отрабатывать - 1"
                }
            ],
            "endTime": 1682837995512,
            "message": "",
            "name": "E:\\projects\\HH\\checkup-extension\\checker-js\\submission\\test.js",
            "startTime": 1682837994785,
            "status": "passed",
            "summary": ""
        }
    ],
    "wasInterrupted": false
}

**Comment by SAKorney** [comment]
Взаимодействие с проверяющей средой налажена на примере задач на вёрстку. Аналогично будет для задач на JS.
